<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Product>SQL Server Backup Suite</Product>
    <Authors>SqlBackup</Authors>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
